jobs:
  include:
    - stage: test
      language: node_js
      node_js:
        - '10'
      install:
        - npm ci
    - stage: deploy
      if: branch = production
      language: node_js
      node_js:
        - '10'
      before_script:
        - openssl aes-256-cbc -K $encrypted_c30a1ec0d033_key -iv $encrypted_c30a1ec0d033_iv -in deploy/.webtask.enc -out "$HOME/.webtask" -d
        - npm install -g wt-cli
      script: wt-cli update mbarber-scraper index.js

notifications:
  email:
    on_success: change
    on_failure: always
